#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : makedepend
Version  : 1.0.6
Release  : 12
URL      : http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.6.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.6.tar.gz
Source99 : http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.6.tar.gz.sig
Summary  : Create dependencies in Makefiles
Group    : Development/Tools
License  : MIT-Opengroup
Requires: makedepend-bin = %{version}-%{release}
Requires: makedepend-license = %{version}-%{release}
Requires: makedepend-man = %{version}-%{release}
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
makedepend - create dependencies in makefiles
---------------------------------------------

%package bin
Summary: bin components for the makedepend package.
Group: Binaries
Requires: makedepend-license = %{version}-%{release}

%description bin
bin components for the makedepend package.


%package license
Summary: license components for the makedepend package.
Group: Default

%description license
license components for the makedepend package.


%package man
Summary: man components for the makedepend package.
Group: Default

%description man
man components for the makedepend package.


%prep
%setup -q -n makedepend-1.0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557095488
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557095488
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/makedepend
cp COPYING %{buildroot}/usr/share/package-licenses/makedepend/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/makedepend

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/makedepend/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/makedepend.1
