#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : makedepend
Version  : 1.0.5
Release  : 9
URL      : http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: makedepend-bin
Requires: makedepend-doc
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
makedepend - create dependencies in makefiles
All questions regarding this software should be directed at the
Xorg mailing list:

%package bin
Summary: bin components for the makedepend package.
Group: Binaries

%description bin
bin components for the makedepend package.


%package doc
Summary: doc components for the makedepend package.
Group: Documentation

%description doc
doc components for the makedepend package.


%prep
%setup -q -n makedepend-1.0.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523287504
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1523287504
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/makedepend

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
